server:
  port: 9003
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.43.100:3306/employees?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
  jpa:
    database: MySQL
    show-sql: true


